apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketchat-config
  namespace: atividade
  labels:
    app: rocketchat
data:
  PORT: "3001"
  ROOT_URL: http://localhost:3001
  MONGO_URL: mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017/rocketchat?replicaSet=rs0
  MONGO_OPLOG_URL: mongodb://mongo-0.mongo,mongo-1.mongo:27017:27017/local
  MAIL_URL: smtp://smtp.email