apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: atividade
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: volume-db
      volumes:
        - name: volume-db
          persistentVolumeClaim:
            claimName: postgres-pvc
