apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  namespace: atividade
spec:
  type: LoadBalancer
  ports:
    - name: portapostg
      port: 5432
      targetPort: 5432
  selector:
   app: postgres
