apiVersion: v1
kind: Service
metadata:
  name: rocketchat
  labels:
    app: rocketchat
  namespace: atividade
spec:
  type: LoadBalancer
  ports:
    - name: portarocket
      port: 3001
      targetPort: 3001
  externalIPs:
    - 192.168.49.2
  selector:
   app: rocketchat