apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
  namespace: atividade
spec:
  type: LoadBalancer
  ports:
    - name: portamongo
      port: 27017
      targetPort: 27017
  selector:
   app: mongo