apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: atividade
spec:
  selector:
    matchLabels:
      app: mongo 
  serviceName: "mongo"
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:4.0
        ports:
        - containerPort: 27017
        command: ["mongod"]
        args: ["--replSet","rs1","--oplogSize","128","--storageEngine=mmapv1"]
        volumeMounts:
        - name: mongo-pvt
          mountPath: /data/db      
  volumeClaimTemplates:
  - metadata:
      name: mongo-pvt
      annotations:
        volume.beta.kubernetes.io/storage-class: "storage-mongo"
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 1Gi
